### ISSUE TITLE
Division durch 0 in einheitsvektor()

### ISSUE THREAD

**Issue by TapferesSchneiderlein** [tpe-lecture/group-14#4]
Eine solche Division wird in der Methode einheitsvektor() nicht abgefangen.

**Comment by SattelMichael** [comment]
Was soll denn bei der Division durch 0 ausgeführt/ ausgegeben werden?

**Comment by TapferesSchneiderlein** [comment]
Ich zitiere mal Herrn Smits:

Da wir noch keine Exceptions haben, ist null wahrscheinlich eine brauchbare Lösung. Später würde man natürlich eine Ausnahme werfen.

**Comment by TapferesSchneiderlein** [comment]
In diesem Fall würde ich eine IllegalArgumentException o.ä. werfen.
