### ISSUE TITLE
Anlegen von neuen Vektoren über Default-Konstruktor

### ISSUE THREAD

**Issue by TapferesSchneiderlein** [tpe-lecture/group-14#5]
Üblicherweise legt man die neuen Vektoren nicht über einen Zugriff auf die privaten Attribute an. Obwohl syntaktisch korrekt, ist dies fehleranfällig.

Anstatt:

```java
 Vector result = new Vector();

 result.x = this.x + vector.x;
 result.y = this.y + vector.y;
 result.z = this.z + vector.z;

return result;
````

würde man schreiben

```java
return new Vector(
    this.x + vector.x,
    this.y + vector.y,
    this.z + vector.z);
````

**Comment by SattelMichael** [comment]
Bei der 'Multiplikation mit einem anderen Vektor' kann dies aber nicht anders ausgedrückt werden, oder? 

Der Rückgabewert ist schließlich kein Objekt sondern das Produkt aus den miteinander multiplizierten Achsenwerten.

**Comment by TapferesSchneiderlein** [comment]
Du meinst die Skalarmultiplikation zweier Vektoren?
Du gibst dir die Antwort eigentlich schon selbst ;-) . Der Rückgabewert ist ein double, kein Objekt vom Typ Vector. Warum also überhaupt den Vektor result anlegen? Um die Werte zwischenzuspeichern (das ist ja der einzige Zweck von result in eurer Lösung), kannst du Hilfsvariablen vom Typ double verwenden. Oder du schreibst das Ganze gleich in einer Zeile (dann aber am besten Klammern verwenden, damit mans noch gut lesen kann).

**Comment by SattelMichael** [comment]
*BrettVormKopf* Danke ! :)
