### ISSUE TITLE
Redundanter Code im Konstruktor

### ISSUE THREAD

**Issue by TapferesSchneiderlein** [tpe-lecture/group-14#6]
Anstatt zu schreiben

```java
public Vector() {
		this.x = 0.0;
		this.y = 0.0;
		this.z = 0.0;
	}
````
sollte dieser Konstruktor mit ````this```` an den anderen mit den gewünschten Werten als Parameter delegieren.

**Comment by SattelMichael** [comment]
Habe das nun angepasst. Ist der Aufruf der Instanzierung eines Nullvektors, über den Parameter-Konstruktor, so in Ordnung:

public Vector() {
		new Vector(0.00, 0.00, 0.00);
	}

?

**Comment by TapferesSchneiderlein** [comment]
Nein, so setzt du eigentlich gar keine Werte, sondern legst innerhalb des Konstruktors eine Vektorinstanz an, die in keiner Variablen gespeichert und auch gar nicht gebraucht wird. Du kannst da beliebige Werte reinschreiben, es wird sich an deinem Null-Vektor nichts ändern. Der Grund, dass die Unit-Tests erfolgreich sind, ist der, dass der Defaultwert von ````double = 0.0```` ist. So gesehen könntest du den Konstruktor also auch einfach leer lassen, sauberer und lesbarer ist aber folgende Lösung:

```java
public Vector() {
    this(0.0, 0.0, 0.0);
}
````
